# Generated by Django 4.2.4 on 2023-08-11 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentPortal', '0002_registration_delete_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='photo',
        ),
        migrations.AlterField(
            model_name='registration',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
