# Generated by Django 4.2.4 on 2023-08-11 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentPortal', '0005_alter_registration_confirm_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='photo',
            field=models.ImageField(default='default_photo.jpg', upload_to='photos/'),
        ),
    ]
