# Generated by Django 4.2.4 on 2023-08-11 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentPortal', '0007_alter_registration_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='photo',
            field=models.ImageField(upload_to='photos/'),
        ),
    ]
