# Generated by Django 4.2.4 on 2023-08-11 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentPortal', '0009_program_student_delete_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='confirm_password',
            field=models.CharField(default=12345, max_length=100),
            preserve_default=False,
        ),
    ]
