# Generated by Django 4.2.4 on 2023-08-12 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudentPortal', '0012_program_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program',
            old_name='student',
            new_name='email',
        ),
    ]
