# Generated by Django 4.2.4 on 2023-08-12 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentPortal', '0018_program_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='faculty_division',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='level_of_study',
            field=models.CharField(choices=[('MSc', 'Master of Science'), ('PhD', 'Doctor of Philosophy')], default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='program_name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Program',
        ),
    ]
