# Generated by Django 4.2.4 on 2023-08-12 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StudentPortal', '0020_program_remove_student_faculty_division_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='student',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='StudentPortal.student'),
            preserve_default=False,
        ),
    ]
